ALTER TABLE `items`
	ADD COLUMN `price` int(11) NOT NULL DEFAULT 0
;

INSERT INTO items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES
('WEAPON_ADVANCEDRIFLE', 'Advanced Rifle', 1, 0, 1, 0),
('WEAPON_APPISTOL', 'AP Pistol', 1, 0, 1, 0),
('WEAPON_ASSAULTRIFLE', 'Assault Rifle', 1, 0, 1, 0),
('WEAPON_ASSAULTSHOTGUN', 'Assault Shotgun', 1, 0, 1, 0),
('WEAPON_ASSAULTSMG', 'Assault SMG', 1, 0, 1, 0),
('WEAPON_AUTOSHOTGUN', 'Auto Shotgun', 1, 0, 1, 0),
('WEAPON_BALL', 'Ball', 1, 0, 1, 0),
('WEAPON_BAT', 'Bat', 1, 0, 1, 0),
('WEAPON_BATTLEAXE', 'Battle Axe', 1, 0, 1, 0),
('WEAPON_BOTTLE', 'Bottle', 1, 0, 1, 0),
('WEAPON_BULLPUPRIFLE', 'Bullpup Rifle', 1, 0, 1, 0),
('WEAPON_BULLPUPSHOTGUN', 'Bullpup Shotgun', 1, 0, 1, 0),
('WEAPON_BZGAS', 'BZ Gas', 1, 0, 1, 0),
('WEAPON_CARBINERIFLE', 'Carbine Rifle', 1, 0, 1, 0),
('WEAPON_COMBATMG', 'Combat MG', 1, 0, 1, 0),
('WEAPON_COMBATPDW', 'Combat PDW', 1, 0, 1, 0),
('WEAPON_COMBATPISTOL', 'Combat Pistol', 1, 0, 1, 0),
('WEAPON_COMPACTLAUNCHER', 'Compact Launcher', 1, 0, 1, 0),
('WEAPON_COMPACTRIFLE', 'Compact Rifle', 1, 0, 1, 0),
('WEAPON_CROWBAR', 'Crowbar', 1, 0, 1, 0),
('WEAPON_DAGGER', 'Dagger', 1, 0, 1, 0),
('WEAPON_DBSHOTGUN', 'Double Barrel Shotgun', 1, 0, 1, 0),
('WEAPON_DIGISCANNER', 'Digiscanner', 1, 0, 1, 0),
('WEAPON_DOUBLEACTION', 'Double Action Revolver', 1, 0, 1, 0),
('WEAPON_FIREEXTINGUISHER', 'Fire Extinguisher', 1, 0, 1, 0),
('WEAPON_FIREWORK', 'Firework Launcher', 1, 0, 1, 0),
('WEAPON_FLARE', 'Flare', 1, 0, 1, 0),
('WEAPON_FLAREGUN', 'Flare Gun', 1, 0, 1, 0),
('WEAPON_FLASHLIGHT', 'Flashlight', 1, 0, 1, 0),
('WEAPON_GARBAGEBAG', 'Garbage Bag', 1, 0, 1, 0),
('WEAPON_GOLFCLUB', 'Golf Club', 1, 0, 1, 0),
('WEAPON_GRENADE', 'Grenade', 1, 0, 1, 0),
('WEAPON_GRENADELAUNCHER', 'Gernade Launcher', 1, 0, 1, 0),
('WEAPON_GUSENBERG', 'Gusenberg', 1, 0, 1, 0),
('WEAPON_HAMMER', 'Hammer', 1, 0, 1, 0),
('WEAPON_HANDCUFFS', 'Handcuffs', 1, 0, 1, 0),
('WEAPON_HATCHET', 'Hatchet', 1, 0, 1, 0),
('WEAPON_HEAVYPISTOL', 'Heavy Pistol', 1, 0, 1, 0),
('WEAPON_HEAVYSHOTGUN', 'Heavy Shotgun', 1, 0, 1, 0),
('WEAPON_HEAVYSNIPER', 'Heavy Sniper', 1, 0, 1, 0),
('WEAPON_HOMINGLAUNCHER', 'Homing Launcher', 1, 0, 1, 0),
('WEAPON_KNIFE', 'Knife', 1, 0, 1, 0),
('WEAPON_KNUCKLE', 'Knuckle Dusters ', 1, 0, 1, 0),
('WEAPON_MACHETE', 'Machete', 1, 0, 1, 0),
('WEAPON_MACHINEPISTOL', 'Machine Pistol', 1, 0, 1, 0),
('WEAPON_MARKSMANPISTOL', 'Marksman Pistol', 1, 0, 1, 0),
('WEAPON_MARKSMANRIFLE', 'Marksman Rifle', 1, 0, 1, 0),
('WEAPON_MG', 'MG', 1, 0, 1, 0),
('WEAPON_MICROSMG', 'Micro SMG', 1, 0, 1, 0),
('WEAPON_MINIGUN', 'Minigun', 1, 0, 1, 0),
('WEAPON_MINISMG', 'Mini SMG', 1, 0, 1, 0),
('WEAPON_MOLOTOV', 'Molotov', 1, 0, 1, 0),
('WEAPON_MUSKET', 'Musket', 1, 0, 1, 0),
('WEAPON_NIGHTSTICK', 'Police Baton', 1, 0, 1, 0),
('WEAPON_PETROLCAN', 'Petrol Can', 1, 0, 1, 0),
('WEAPON_PIPEBOMB', 'Pipe Bomb', 1, 0, 1, 0),
('WEAPON_PISTOL', 'Pistol', 1, 0, 1, 0),
('WEAPON_PISTOL50', 'Police .50', 1, 0, 1, 0),
('WEAPON_POOLCUE', 'Pool Cue', 1, 0, 1, 0),
('WEAPON_PROXMINE', 'Proximity Mine', 1, 0, 1, 0),
('WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 1, 0, 1, 0),
('WEAPON_RAILGUN', 'Rail Gun', 1, 0, 1, 0),
('WEAPON_REVOLVER', 'Revolver', 1, 0, 1, 0),
('WEAPON_RPG', 'RPG', 1, 0, 1, 0),
('WEAPON_SAWNOFFSHOTGUN', 'Sawn Off Shotgun', 1, 0, 1, 0),
('WEAPON_SMG', 'SMG', 1, 0, 1, 0),
('WEAPON_SMOKEGRENADE', 'Smoke Gernade', 1, 0, 1, 0),
('WEAPON_SNIPERRIFLE', 'Sniper Rifle', 1, 0, 1, 0),
('WEAPON_SNOWBALL', 'Snow Ball', 1, 0, 1, 0),
('WEAPON_SNSPISTOL', 'SNS Pistol', 1, 0, 1, 0),
('WEAPON_SPECIALCARBINE', 'Special Rifle', 1, 0, 1, 0),
('WEAPON_STICKYBOMB', 'Sticky Bombs', 1, 0, 1, 0),
('WEAPON_STINGER', 'Stinger', 1, 0, 1, 0),
('WEAPON_STUNGUN', 'Police Taser', 1, 0, 1, 0),
('WEAPON_SWITCHBLADE', 'Switch Blade', 1, 0, 1, 0),
('WEAPON_VINTAGEPISTOL', 'Vintage Pistol', 1, 0, 1, 0),
('WEAPON_WRENCH', 'Wrench', 1, 0, 1, 0)
;